name: 🐛 Hata Raporlama
description: Hata gönderimi yapmak için sade şablon
title: "[TASK]: "
labels: ["draft", "task", "pending"]
assignees: ["gokhanozdemir"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: sprint
    attributes:
      label: Hangi sprintte çalışıyorsunuz?
      description: "Lütfen çalıştığınız sprinti seçin."
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
        - Sprint 4
        - Sprint 5
        - Sprint 6
        - Sprint 7
        - Sprint 8
        - Sprint 9
        - Sprint 10
        - Sprint 11
        - Sprint 12
        - Sprint 13
        - Sprint 14
        - Sprint 15
        - Sprint 16
        - Sprint 17
        - Sprint 18
        - Sprint 19
        - Sprint 20
        - Sprint 21
        - Sprint 22
        - Sprint 23
        - Sprint 24
    validations:
      required: true
  - type: dropdown
    id: day
    attributes:
      label: Hangi gün?
      description: "Lütfen hatayla karşılaştığınız günü seçin."
      options:
        - Day 1
        - Day 2
        - Day 3
        - Day 4
        - Day 5
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?
      description: "Lütfen adım adım hata ile hansıl karşılaştığınızı, kendi tarafımızda yeniden oluşturabilmek için adım adım anlatın. Gerekirse ekran görüntüsü ekleyebilirsini, araç menüsündeki 'ataç' ikonuna basarak ekran görüntüsü ekleyebilirsiniz."
      value: |
        1.
        2.
        3.
        ...
      placeholder: Lütfen adım adım listeleyin.
    validations:
      required: true
